project_id = "jdiowphmzsqvpizlwlzn"

[functions.manage-users]
verify_jwt = false

[functions.rag-feeder]
verify_jwt = true

[functions.work-order-parse]
verify_jwt = true

[functions.truck-notes]
verify_jwt = false

[functions.auth-emails]
verify_jwt = false

[functions.send-email]
verify_jwt = false